#!/usr/bin/env php
C:\xampp\php php
<?php
/*|-----------------------------------------------------------------|*/
/* require(__DIR__.'/vendor/autoload.php'); */
require( __DIR__ . DIRECTORY_SEPARATOR . 'app' . DIRECTORY_SEPARATOR . 'bootstrap.php' );
/*|-----------------------------------------------------------------|*/
/* $application = new \Symfony\Component\Console\Application(); */
/*|-----------------------------------------------------------------|*/
/* $application->addCommands(new Helphp\Create\ClassCommand()); */
$application = $container['application'];
/*|-----------------------------------------------------------------|*/
$application->run();
?>